### ISSUE TITLE
Namespaces error

### ISSUE THREAD

**Issue by rvanlaak** [pusher/pusher-http-php#144] opened 2017-07-13 18:09 UTC
Our build process throws the following exception

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Pusher" from the global namespace.
Did you forget a "use" statement for "Pusher\Pusher"? in /builds/acme/vendor/laupifrpar/pusher-bundle/DependencyInjection/PusherFactory.php:26
Stack trace:
#0 /tmp/test/appTestDebugProjectContainer.php(5358): Lopi\Bundle\PusherBundle\DependencyInjection\PusherFactory::create(Array)
#1 /builds/acme/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(311): appTestDebugProjectContainer->getLopiPusher_PusherService()
#2 /tmp/test/appTestDebugProjectContainer.php(8112): Symfony\Component\DependencyInjection\Container->get('lopi_pusher.pus...')
#3 /builds/acme/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(311): appTestDebugProjectContainer->getAcme_Entity_AvailabilitySubscriberService()
#4 /tmp/test/appTestDebugProjectContainer.php(2830): Symfony\Component\DependencyInjection\Container->get('scri in /builds/acme/vendor/laupifrpar/pusher-bundle/DependencyInjection/PusherFactory.php on line 26
```

The `laupiFrpar/LopiPusherBundle` does not have the `3.0.0` dependency though:

> "pusher/pusher-php-server": ">=2.2.1"

... so, maybe this can be fixed and released as 2.6.5 so the bundle does not break.

**Comment by GrahamCampbell** [comment] 2017-07-13 20:08
This is a bug in that bundle. It should have used the version constraint `^2.2.1`. Too late to fix incorrect version constraints, since composer can just resolve the version where the version constraint had now upper bound in order to satisfy dependencies.

TLD: Always have an upper bound, since there's no going back.

**Comment by GrahamCampbell** [comment] 2017-07-13 20:08
This is not a bug in this library, so this issue should be closed. Please report to `laupiFrpar/LopiPusherBundle`.

**Comment by luismfonseca** [comment] 2017-07-13 21:24
I agree with @GrahamCampbell here. We added namespacing and released a new major version, so there's nothing more we can do on this side.

Btw, I like how PHP actually gives a helpful message in this case:
> Did you forget a "use" statement for "Pusher\Pusher"? in /builds/acme/vendor/laupifrpar/pusher-bundle/DependencyInjection/PusherFactory.php:26

At any rate, I'm closing this but feel free to continue the conversation.

**Closed by luismfonseca** 2017-07-13 21:24 UTC

**Comment by GrahamCampbell** [comment] 2017-07-14 22:06
> Btw, I like how PHP actually gives a helpful message in this case:

PHP did not give a helpful error message I suspect this is actually Symfony's error handler doing this.
