### ISSUE TITLE
status 0

### ISSUE THREAD

**Issue by masoud-moghini** [pusher/pusher-http-php#190] opened 2018-08-17 18:27 UTC
[here](https://github.com/laravel/framework/issues/25218) a problem brought up about laravel .but it seems to be a problem with pusher .pushre responds with 
```
{
    'body':false,
    'status':0
}
```
in [pusher rest api](https://pusher.com/docs/rest_api) nothing said about status 0.

**Comment by WillSewell** [comment] 2018-08-23 16:38
Thanks for reporting this issue. Could you send me a minimal example using pusher-http-php which reproduces this problem? Thanks.

**Comment by masoud-moghini** [comment] 2018-08-27 19:33
thank Will and sorry for latency I am actually using laravel and here is the part that usis pusher-php-server ,which I think is a fork of pusher-http-php,
```
use Pusher\Pusher;

    public function broadcast(array $channels, $event, array $payload = [])
    {
        $socket = Arr::pull($payload, 'socket');

        
        $response = $this->pusher->trigger(
            $this->formatChannels($channels), $event, $payload, $socket, true
        );

        if ((is_array($response) && $response['status'] >= 200 && $response['status'] <= 299)
            || $response === true) {
            return;
        }

        \Log::error($response);
        throw new BroadcastException(
            is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
        );
    }
```
If it does not concern this library please guide me what I do .
thanks so much

**Comment by WillSewell** [comment] 2018-08-29 15:29
I just ran this code with php 7.2.9, Laravel 5.6.17 and pusher-http-server 3.0.1:

```php
        $pusher = $pusher = new Pusher( 'my-key', 'my-secret', 'my-app-id', array('cluster' => 'mt1') );
        $response = $pusher->trigger(
            ['test-channel'], 'test-event', 'test-payload', null, true
        );

        if ((is_array($response) && $response['status'] >= 200 && $response['status'] <= 299)
            || $response === true) {
            return;
        }

        \Log::error($response);
        throw new BroadcastException(
            is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
        );
```

and there were no issues.

**Comment by WillSewell** [comment] 2018-10-18 13:44
Closing because I was unable to reproduce.

**Closed by WillSewell** 2018-10-18 13:44 UTC

**Comment by raphaelbeckmann** [comment] 2018-12-17 08:18
Had the same problem and solved it by setting `PUSHER_APP_CLUSTER=eu` in the `.env`.
