### ISSUE TITLE
Doesn't work with EU cluster

### ISSUE THREAD

**Issue by julien-digilink** [pusher/pusher-http-php#28] opened 2015-02-15 18:49 UTC
I get "Unknown auth key" when I try to use that lib.
But it works when I modify the source and make the api calls this url : http://api-eu.pusher.com(...)

**Comment by leggetter** [comment] 2015-03-03 15:50
@julien-digilink I can't replicate this. I've just done some testing using both the new `$options` parameter and via the legacy parameter.

### $options

```php
$options = array(
  'host' => HOST
);
$this->pusher = new Pusher(AUTHKEY, SECRET, APPID, $options );
```

### Legacy

```php
$this->pusher = new Pusher(AUTHKEY, SECRET, APPID, DEBUG, HOST);
```

Which way are you trying to achieve this? What do you see in the [debug log](https://github.com/pusher/pusher-http-php#debugging--logging)?

**Comment by leggetter** [comment] 2015-03-17 21:30
@julien-digilink I'm closing this as I can't reproduce. Please re-open if you can and please provide an example that demonstrate it. Thanks.

**Closed by leggetter** 2015-03-17 21:30 UTC
