### ISSUE TITLE
Symfony issue with pusher recipe

### ISSUE THREAD

**Issue by lpj145** [pusher/pusher-http-php#187] opened 2018-08-01 20:49 UTC
Hi guys, god job, when i try connect with recipe to symfony, pusher api say "unknow auth key", i think because recipe cannot receive a cluster region to login, i'm try without recipe and works right, please review this recipe and test it.

**Comment by WillSewell** [comment] 2018-08-03 15:43
Hi, could you please post the code which reproduces this problem?

**Comment by WillSewell** [comment] 2018-10-18 13:45
Unable to reproduce, closing.

**Closed by WillSewell** 2018-10-18 13:45 UTC
