### ISSUE TITLE
ParagonIE_Sodium_Compat.php is missing

### ISSUE THREAD

**Issue by tidus2102** [pusher/pusher-http-php#216] opened 2019-04-18 08:05 UTC
Hi, I got this error when the lib (v3.4.1) with Composer autoload.php

> include(ParagonIE_Sodium_Compat.php): failed to open stream: No such file or directory

PHP Code:
`require_once 'autoload.php';`

composer.json:
`{
    "require": {
        "pusher/pusher-php-server": "^3.4.1"
    }
}`

Testing with PHP 7.2.11

**Comment by WillSewell** [comment] 2019-05-03 09:55
I can't reproduce this issue. Could you upload your complete project please? (e.g. in a tarball, preferably containing a Dockerfile)

**Comment by WillSewell** [comment] 2019-06-17 10:20
Closing because I am unable to reproduce. I will re-open if I hear back about this.

**Closed by WillSewell** 2019-06-17 10:20 UTC
