### ISSUE TITLE
metadata.user_id is undefined in presenceChannel.bind()

### ISSUE THREAD

**Issue by mlammert** [pusher/pusher-http-php#275] opened 2021-02-17 22:24 UTC
Have been playing around with presence- channels and everything seems to be working correctly.

I can authenticate and provide a user_id and a user_info.

If I use:
`presenceChannel.members.each(function(member) {
...
}):`

I can get a list of all the users and their associated id's and info as provided during authentication.

However, if I try to access metadata.user_id from 
`presenceChannel.bind('my-event', function (data, metadata) {
...
});`

I get `metadata.user_id = undefined`. metadata is just an empty object.

Any ideas why?

**Comment by ben-pusher** [comment] 2021-02-18 12:09
Hi, 
The metadata will only be populated when sending or receiving client-events, a special type of event that is sent from our client libraries. You can read about these in [our documentation](https://pusher.com/docs/channels/using_channels/events#triggering-client-events). As your event is not prefixed with `client-` it would appear you are not binding to a client event here.

**Comment by mlammert** [comment] 2021-02-18 15:36
Thank you for the quick reply. I looked up all the info on client- events and got it all working. Thank you for pointing me in the right direction.

I do have some questions though:

I don't full understand the "need" or the "difference" between client- events and non-client- events. I can use trigger() either client side or server side. Is there some sort of pros/cons lists of client- events and non-client- events? What would be a use case for using one over the other?

In an example like a group chat application, wouldn't I want to use non-client- events? But, then if I use non-client- events, how would I know who is typing what, in a group chat scenario?

Is there a way to include the user_id if we send a message via the server?
PHP: `$objPusher->trigger('presence-test-channel', 'client-test-event', array('message' => 'test message'));`

Thank you!

**Comment by elverkilde** [comment] 2021-03-09 22:53
Hi @mlammert,

The terminology can quickly become confusing (everything is a client), so in the following I will call software implementing the server SDK a "publisher" and software implementing the client/websocket SDK a "subscriber". Publishers can (only) send non-client events and subscribers can (only) send client events.

Let me first start with saying that the "missing" user info is by design, as it would be wasteful to pass around the metadata for every event on a presence channel (it doesn't change). If it will be used later, the subscriber should store the user info it receives when it first "sees" a channel member.

The follow-up question is an interesting one and I think you have pretty much answered the question yourself. Besides convenience (you don't need "extra" logic in the publisher) client events re-use the token from the auth endpoint. This token is signed by your server, meaning a user can't change the contents undetected [1]. If this wasn't the case, a malicious user would be able to e.g. impersonate another user.

If you are implementing this with a non-client event, the user would presumable have an authenticated session with your server. The payload you send is simply a JSON object, so there wouldn't be anything in the way of passing in a user id in that payload, e.g.:

```
$payload = [
  'user_id' => $user-id-from-session,
  'message' => 'test message'
];
$objPusher->trigger('presence-test-channel', 'test-event', $payload);
```

However, the Pusher SDK cannot help you with this. The only concept of a user identity the Pusher system has is the signed identity coming from the auth endpoint, which is sent to a subscriber. This is also the reason why the publisher cannot send a client event; there is no pre-defined way to link a server session with a user.

I don't see a reason to not use client events for the use case you describe (chat messages originating from other users). It's a common use case for client events.


[1]: Your server and Pusher share a secret, allowing Pusher to verify the signature. Messages with an invalid signature won't be published.

**Comment by elverkilde** [comment] 2021-03-10 13:10
I am closing this with the answers above, but feel free to re-open if you still have questions.

**Closed by elverkilde** 2021-03-10 13:10 UTC
Labels: question
